name: Build and Deploy
on:
  push: 
    branches: []

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: LFS Checkout
        run: git lfs pull

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Yarn install
        uses: bahmutov/npm-install@v1.1.0

      - name: Build
        run: yarn run build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        if: github.ref == 'refs/heads/main'
        with:
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          